spring:
  application:
    name: kaoyuapi
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.99.218:3306/kaoyuapi
    username: cky
    password: cky
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password: 12345678
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
kaoyuapi:
  client:
    access-key: 68b79cde8312d99e21be7fe395d81ae2
    secret-key: 33904d08f4a9a43de555af5bf989cb8b
dubbo:
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
  application:
    name: kaoyuapi
  protocol:
    name: dubbo
    port: -1
